//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departs_Tasks
    {
        public int Проект { get; set; }
        public int Отдел { get; set; }
        public string Задача_отделу { get; set; }
        public System.DateTime Срок_выполнения_задачи { get; set; }
        public Nullable<System.DateTime> Реальный_срок { get; set; }
    
        public virtual Depart Depart { get; set; }
        public virtual Project Project { get; set; }
    }
}
