//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers_Tasks
    {
        public int Проект { get; set; }
        public int Сотрудник { get; set; }
        public string Задача { get; set; }
        public System.DateTime Срок_выполнения { get; set; }
        public int Статус { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
